### ISSUE TITLE
How to configure the environment for the evaluation part of the DSPM system

### ISSUE THREAD

**Issue by ywlt** [WukLab/Hotpot#5]
Specifically, how to port MongoDB to Hotpot, and how to modify the code.I would be grateful if you could give specific steps.
Thanks!

**Comment by lastweek** [comment]
Hi @ywlt ,

Thank you for your interests on using Hotpot. You can follow the README file to setup and run Hotpot, once Hotpot is running, you will be able to run the simple [test code](https://github.com/WukLab/Hotpot/blob/master/hotpot/test/seq.c), and get perf numbers.

Our in-house modification to MongoDB is not open-sourced, because we don't think it has the open-source quality. But here are some notes I could share with you:


> Since MongoDB v2.7.0 is already doing mmap, we just use that with a special flag to tell Hotpot that this file is intended for Hotpot store. After that, we collect all the information about updated regions (offset and size) in MongoDB, and during MongoDB's flush, we replace MongoDB's original flushing method to issuing a "commit" of these collected regions to Hotpot using msync (check Hotpot paper for the exact APIs). Most of the changes are in src/mongo/db/dur.cpp.

Sorry for the inconvenience, hope this helps.

**Comment by ywlt** [comment]
Is it only necessary to modify the code of MongoDB? Does Hopot's code need to be modified?

**Comment by lastweek** [comment]
Hi @ywlt,

It is only necessary to patch MongoDB, you don't need to change Hotpot. Hotpot is ready to use by all applications once deployed.

**Comment by ywlt** [comment]
I have found all kinds of information about MongoDB on the Internet these days, but I really don't know where to modify.Because I just learned about MongoDB a little.  I don't know if you can give me more detailed information. Because I really want to run the test part and then learn the DSPM system.
Thank you!
